### ISSUE TITLE
Unable to Authorize with Plex

### ISSUE THREAD

**Issue by secretlycarl** [DialmasterOrg/Youtarr#79]
Hi, I can't authorize with Plex. It directs me to auth with Plex and it works on the plex site, but then Youtarr says "Invalid Plex Account. You must use the Plex account associated to this Youtarr server." I'm running this in docker on windows. Here is my config file:

{
  "initialSetup": true,
  "channelFilesToDownload": 5,
  "channelAutoDownload": false,
  "channelDownloadFrequency": "0 * * * *",
  "plexIP": "host.docker.internal",
  "plexApiKey": "[my plex API key]",
  "plexYoutubeLibraryId": "16",
  "youtubeOutputDirectory": "E:\\Videos\\YouTube",
  "uuid": "[my plex library UUID]",
  "//comment": "Replace the two directory paths below with YOUR paths to run this on Windows and have it work",
  "devYoutubeOutputDirectory": "E:\\Videos\\YouTube",
  "devffmpegPath": "C:\\PATH\\ffmpeg.exe",
  "//youtubeApiKey_comment": "You can get a Youtube API key here: https://console.developers.google.com/apis/credentials",
  "youtubeApiKey": "[my google /yt API key]"
}

the console in Docker shows it checking the pin but nothing happens.

I tried switching the host.docker.internal to my plex server IP but that just gave more errors and looped trying to check credentials. Is there any other file i need to edit or something to change in the config files? thanks

Edit: after more poking around and asking google gemini, it says that "If your Plex server is running natively on your Windows machine (not in Docker), replace "host.docker.internal" with the actual IP address of your machine on your local network.". Could also be something to do with my VPN and split tunneling.

**Comment by dialmaster** [comment]
Is this your first initial setup, or was it previously working and then stopped?
I had a security issue that I found this weekend where it would allow ANYONE with a Plex account to auth with Plex and access your running youtarr (if it was exposed outside your internal network), and I fixed it. If it was previously working for you, maybe I broke something.

Also, did the change you suggested, using the actual IP address, fix it?

You are running on Windows, is youtarr running on the same machine as Plex?
Also, are you starting up youtarr using ./start.sh (which starts it up using Docker)?

The Plex account you AUTH with needs to be the SAME as the Plex server that you are connecting to.

Also, try this:
1) Shut down youtarr
2) Copy your config.json to a backup config.json.backup (to restore in case something goes wrong)
3) REMOVE the plexApiKey string from your config.json, so it should look like this:
```
"plexApiKey": "",
```
4) Restart youtarr
5) Attempt to auth again (this basically redoes a "first time setup" and uses the API key it gets from the auth attempt to set the value in the config)

If that works, you can doublecheck by opening an incognito window and attempting to login again using your plex credentials... and it should still work.

**Comment by secretlycarl** [comment]
Thanks for the reply!

This is my first time setting it up, and one of my first experiences with Docker. Changing the IP to my actual IP did not fix it. Yes, youtarr and Plex are on the same machine, and I'm starting it with start.sh each time and I see it appear in docker (I would delete it from docker each time to try and fix it and start over). I'll try what you suggested.

Edit: that fixed it, thank you! It's working now.

**Comment by dialmaster** [comment]
I'm glad that helped. I am updating the Readme in case someone else has the same issue. See: https://github.com/DialmasterOrg/Youtarr/commit/0a18d108735a1287168c8c7b6dd2b2714e672cc8
