### ISSUE TITLE
Odd season/episode behaviour?

### ISSUE THREAD

**Issue by DeanAtEC** [DialmasterOrg/Youtarr#86]
Sorry for being annoying today, but just noticed something else with the videos in Plex. I'm not sure if it's expected behaviour or not, but I'm seeing one "season" per episode. And the season numbers are all over the map (1, 3, 5, 16, 29, etc). Is this expected? Would be nice to be able to say group them into a "season" based on the release year of the video maybe.

Still no posters showing up, and I've confirmed they are present, but Plex is so far refusing to show them :( Plex is generating thumbnails for the videos and using them now, instead of the actual poster.jpg images. I've confirmed the agent settings for the library are to prefer local assets, still nothing. But that is a Plex problem :)

**Comment by dialmaster** [comment]
Ah, what agent are you using for the library settings? I use "Other Videos" and "Personal Media" and it seems to pick up the posters:
![image](https://github.com/user-attachments/assets/3fc112d3-3ca9-496b-afc2-ad4e3f0ada91)

![image](https://github.com/user-attachments/assets/0f44681e-3cfa-44d0-9e6c-ce8738883181)

**Comment by DeanAtEC** [comment]
Wow, that made all the difference! I'm guessing there is no nice/easy way to group them? I see you can choose Folders instead of Movies, but then you lose images again. Anyway, much better than before, perhaps I'll add a feature request for TV show-like grouping or somehow grouping them under the channel name, etc. Thanks again!

**Comment by dialmaster** [comment]
I gave you a shoutout in the Readme, thanks for helping me to make this better!
![image](https://github.com/user-attachments/assets/64ed85d0-0f08-44c0-883d-b9007756ddf4)
